//@version=6
indicator('Market State Tracker', 'MST', false, precision = 4, timeframe = '', timeframe_gaps = true)
//by gorx1


//  dependencies........................................................................................................
relative_revision(float datapoint, int length) =>
    var float mean = na
    var float rr   = na

    if length == 1
        mean := na
        rr   := na

    if not na(datapoint)
        if na(mean)
            mean := datapoint
            rr   := 1
        else
            alpha = 1 / length
            mean := alpha * datapoint + (1 - alpha) * mean
            rr   := datapoint / mean


    nz(rr, 1)


vapm(data, length) =>  //  Volume Acceleration Price Model
    model =  length == 1 ?     na                                         :
             length == 2 ?                data[1]                         :
             length == 3 ?            2 * data[1] -     data[2]           : 
                                      3 * data[1] - 3 * data[2] + data[3] 

    extra =  length == 1 ?     data                                       :
             length == 2 ? 2 * data -     data[1]                         :
             length == 3 ? 3 * data - 3 * data[1] +     data[2]           :
                           4 * data - 6 * data[1] + 4 * data[2] - data[3]

    signal =       math.abs(extra - model)  //  signal dynamics, variability of it
    noise  =       math.abs(data  - model)  //  noise  dynamics, measurement vs baseline truth, variability of measurements
    gain   = nz(signal / (signal + noise))                        

    augment         = gain * extra + (1 - gain) * data
    model_direction = length == 1 ? 0 : (model > data[1] ? 1 : model < data[1] ? -1 : 0)
    revision        = augment - model

    neg_revision_lag  = model_direction > 0 and revision < 0 ? math.abs(revision) : na
    neg_revision_lead = model_direction < 0 and revision < 0 ? math.abs(revision) : na
    pos_revision_lag  = model_direction < 0 and revision > 0 ? math.abs(revision) : na
    pos_revision_lead = model_direction > 0 and revision > 0 ? math.abs(revision) : na

    neg_ri_lag  = relative_revision(neg_revision_lag , length)
    neg_ri_lead = relative_revision(neg_revision_lead, length)
    pos_ri_lag  = relative_revision(pos_revision_lag , length)
    pos_ri_lead = relative_revision(pos_revision_lead, length)
    
    neg_gamma_lag  = math.min(math.max(neg_ri_lag , 1), 12)  //  limiter, the limits are calculated by theoretical MBAD of expo distro
    neg_gamma_lead = math.min(math.max(neg_ri_lead, 1), 12)  //  limiter, the limits are calculated by theoretical MBAD of expo distro
    pos_gamma_lag  = math.min(math.max(pos_ri_lag , 1), 12)  //  limiter, the limits are calculated by theoretical MBAD of expo distro
    pos_gamma_lead = math.min(math.max(pos_ri_lead, 1), 12)  //  limiter, the limits are calculated by theoretical MBAD of expo distro


    [neg_gamma_lag, pos_gamma_lag, neg_gamma_lead, pos_gamma_lead]


universal_adaptive_tracking_online(float data, int length, float gamma) =>
    // beta = pow(1 - sqrt(2) * (2 / (length + 1)), 4)  //  engineering
    // beta = exp(-8 * sqrt(2) / length)  //  engineering 
    beta  = math.exp(-34 / 3 / length)  //  math, moment matched with Extended Beta(2, 2) Window
    alpha = math.pow(beta, gamma)


    state = 0.
    pos   = 0.
    vel   = 0.
    acc   = 0.

    pos   :=          alpha     * nz(pos[1], data) +         (1 - alpha   ) *  data
    vel   :=          beta      * nz(vel[1], 0   ) +         (1 - beta    ) * (data - pos                     )
    acc   := math.pow(alpha, 2) * nz(acc[1], 0   ) + math.pow(1 - alpha, 2) * (pos  + vel - nz(state[1], data))
    state := acc + nz(state[1], data)


    state


round_to_inf (float x, float tick) =>  //  round toward infinity
    math.sign(x) * math.ceil(math.abs(x) / tick) * tick


round(float x, float tick) =>  //  round half up
    math.round(x / tick) * tick
//  dependencies........................................................................................................


//  data interval logic.................................................................................................
anchor  = input.string('Session', 'anchor',
 ['1', '5', '24h', 'Session', 'Year', 'Cumulative', 'Moving window', 'Custom session'], group = 'interval')

length  = input        (64         , 'moving window length' , group = 'interval')
session = input.session('0000-2345', 'custom session period', group = 'interval')
hybrid  = input        (false      , 'hybrid window'        , group = 'interval')

isNewPeriod = switch anchor
    '1'       => timeframe.change('1'   )
    '5'       => timeframe.change('5'   )
    '24h'     => timeframe.change('1440')
	'Session' => timeframe.change('D'   )
	'Year'    => timeframe.change('12M' )

if na(close[1])
	isNewPeriod := true

var barsInSession = 0
barsInSession    := isNewPeriod ? 1 : 1 + barsInSession

var barsInSessionCustom = 0
barsInSessionCustom    := na(time('', session)) ? 1 : 1 + barsInSessionCustom

len = if anchor == 'Cumulative'
    bar_index + 1
else  if anchor == 'Moving window'
    length
else  if anchor == 'Custom session'
    barsInSessionCustom
else
    barsInSession + (hybrid ? length : 0)
//  data interval logic.................................................................................................


//  main................................................................................................................
step_space = input(1    , 'native tick size multiplier' , group = 'data'      ) * syminfo.mintick  //  space has to be ceiled
round      = input(false, 'round levels to closest tick', group = 'parameters')


src = (round_to_inf(high, step_space) + round_to_inf(low, step_space) + round_to_inf(close, step_space)) / 3

[neg_gamma_lag, pos_gamma_lag, neg_gamma_lead, pos_gamma_lead] = vapm(src, len)

neg_state_lag  = universal_adaptive_tracking_online(src, len, neg_gamma_lag )
pos_state_lag  = universal_adaptive_tracking_online(src, len, pos_gamma_lag )
neg_state_lead = universal_adaptive_tracking_online(src, len, neg_gamma_lead)
pos_state_lead = universal_adaptive_tracking_online(src, len, pos_gamma_lead)

neg_state = (neg_state_lag + neg_state_lead) / 2
pos_state = (pos_state_lag + pos_state_lead) / 2

if round
    neg_state := round(neg_state, step_space)
    pos_state := round(pos_state, step_space)
//  main................................................................................................................


//  visuals.............................................................................................................
viz_off = input(0, 'plotting offset', group = 'style')


plot(neg_state , 'neg state' , color.red   , 2, offset = viz_off, force_overlay = true)
plot(pos_state , 'pos state' , color.blue  , 2, offset = viz_off, force_overlay = true)

plot(hlc3 - neg_state, 'price - neg_state', color.red )
plot(hlc3 - pos_state, 'price - pos_state', color.blue)


hline(0)
//  visuals.............................................................................................................


//  ∞
