//@version=6
indicator('Market State Tracker', 'MST', false, precision = 4, timeframe = '', timeframe_gaps = true, max_bars_back = 5000)
//by gorx1


//  dependencies........................................................................................................
type envelope
    float lower
    float upper


leaky_peak_iir(float src, int len, float scale_lower, float scale_upper) =>  //  additive version
    var float upper = na
    var float lower = na

    if len == 1
        lower := na
        upper := na

    if na(upper)
        upper := src
        lower := src
    else
        lower := math.min(src, lower + scale_lower / len)
        upper := math.max(src, upper - scale_upper / len)


    envelope.new(lower, upper)


leaky_peak_fir(float src, int len, float scale_lower, float scale_upper) =>  //  additive version
    upper = -1e16  //  hillbilly a bit, but ok
    lower =  1e16  //  hillbilly a bit, but ok

    acc_sub = 0.0
    acc_add = 0.0

    for i = 0 to len - 1
        lower_contrib = src[i] + acc_add
        upper_contrib = src[i] - acc_sub

        lower := math.min(lower, lower_contrib)
        upper := math.max(upper, upper_contrib)

        step_len = float(len - i)

        step_offset_dn = scale_lower[i] / step_len
        step_offset_up = scale_upper[i] / step_len

        acc_sub := acc_sub + step_offset_up
        acc_add := acc_add + step_offset_dn


    envelope.new(lower, upper)


entropic_filter(float src, int len) =>  //  the diffreence with sma is negligible over narrow data range, but still
    sum_xw = ta.sma(src * math.log(src), len)
    sum_w  = ta.sma(src                , len)

    math.exp(sum_xw / sum_w)


relative_residual_iir(float datapoint, int length) =>
    var float mean = na
    var float rr   = na

    n = 0

    for i = 0 to length - 1
        if not na(datapoint[i])
            n += 1

    if length == 1
        mean := na
        rr   := na
        n    := na

    if not na(datapoint)
        if na(mean)
            mean := datapoint
            rr   := 1
        else
            alpha = 1 / n
            mean := alpha * datapoint + (1 - alpha) * mean
            rr   := datapoint / mean


    nz(rr, 1)


relative_residual_fir(float datapoint, int length) =>
    float last  = na
    sum   = 0.
    sum_w = 0

    for i = 0 to length - 1
        if not na(datapoint[i])
            if na(last)
                last := datapoint[i]

            w = 1

            sum   += w * datapoint[i]
            sum_w += w

    mean = sum / sum_w
    rr   = last / mean


    nz(rr, 1)


universal_adaptive_tracking_online(float data, int length, float gamma) =>
    // beta = pow(1 - sqrt(2) * (2 / (length + 1)), 4)  //  engineering
    // beta = exp(-8 * sqrt(2) / length)  //  engineering 
    beta  = math.exp(-34 / 3 / length)  //  math, moment matched with Extended Beta(2, 2) Window
    alpha = math.pow(beta, gamma)


    state = 0.
    pos   = 0.
    vel   = 0.
    acc   = 0.

    c = 0.5 //  maybe can we refined for a slight improvement tho, but that would be the next dev iteration, can't be bothered now

    pos   := length == 1 ? data :          alpha     * nz(pos[1], data) +         (1 - alpha   ) *  data
    vel   := length == 1 ? 0    :          beta      * nz(vel[1], 0   ) +         (1 - beta    ) * (data - pos                         )
    acc   := length == 1 ? 0    : math.pow(alpha, 2) * nz(acc[1], 0   ) + math.pow(1 - alpha, 2) * (pos  + vel * c - nz(state[1], data))
    state := length == 1 ? data : acc + nz(state[1], data)


    state


universal_adaptive_tracking(float data, int length, float gamma, float innovation = 1) =>
    sum   = 0.
    sum_w = 0.
    
    running_log_x = 0.

    for i = 0 to length - 1
        current_num = length - i
        prev_num    = length - i + 1
        step_ln     = math.log(current_num / prev_num)
    
        running_log_x += gamma[i] * step_ln
        

        x = math.exp(running_log_x)
        
        x2 = math.pow(x, 2)
        x3 = math.pow(x, 3)
        x4 = math.pow(x, 4)
        
        // "brought to you by beta(2, 2), all 5"
        gen =     x3 -  0.5 * x4 //  2nd anti-derivative
        cdf = 3 * x2 -  2   * x3 //  1st anti-derivative
        pdf = 6 * x  -  6   * x2 //  main, from there we go both directions
        fly = 6      -  12  * x  //  1st derivative
        box =          -12       //  2nd derivative

        weight = gen * cdf * pdf * fly * box * math.abs(innovation[i])

        sum   += weight * data[i]
        sum_w += weight
        
    state = sum / sum_w


    state


round_to_inf (float x, float tick) =>  //  round toward infinity
    math.sign(x) * math.ceil(math.abs(x) / tick) * tick


round(float x, float tick) =>  //  round half up
    math.round(x / tick) * tick


vapm(float data, int length, bool online) =>  //  carefull with porting, there's a feedback loop there    
    var envelope = envelope.new(data, data)

    scale_lower = nz(math.abs(data - envelope.lower))
    scale_upper = nz(math.abs(data - envelope.upper))

    anchor_envelope = scale_lower > scale_upper ? 1 : scale_lower < scale_upper ? -1 : 0 

    neg_scale_lead = anchor_envelope == -1 and data < envelope.lower ? scale_lower : na
    neg_scale_lag  = anchor_envelope ==  1 and data < envelope.upper ? scale_upper : na
    pos_scale_lag  = anchor_envelope == -1 and data > envelope.lower ? scale_lower : na
    pos_scale_lead = anchor_envelope ==  1 and data > envelope.upper ? scale_upper : na

    envelope := online ? leaky_peak_iir(data, length, scale_lower, scale_upper) :
                         leaky_peak_fir(data, length, scale_lower, scale_upper)

    neg_rr_lead = online ? relative_residual_iir(neg_scale_lead, length) : relative_residual_fir(neg_scale_lead, length)
    neg_rr_lag  = online ? relative_residual_iir(neg_scale_lag , length) : relative_residual_fir(neg_scale_lag , length)
    pos_rr_lag  = online ? relative_residual_iir(pos_scale_lag , length) : relative_residual_fir(pos_scale_lag , length)
    pos_rr_lead = online ? relative_residual_iir(pos_scale_lead, length) : relative_residual_fir(pos_scale_lead, length)


    [neg_rr_lag, pos_rr_lag, neg_rr_lead, pos_rr_lead, envelope]


soft_max(a, b, p) =>
    math.pow(math.pow(a, p) + math.pow(b, p), 1 / p)
    

soft_min(a, b, p) =>
    math.pow(math.pow(a, -p) + math.pow(b, -p), -1 / p)


compressor(float signal, float lower_limit, float upper_limit, float intensity) =>
    signal_expanded = if signal > 1
        math.pow(signal,     upper_limit)
    else if signal < 1
        math.pow(signal, 1 / lower_limit)
    else
        signal

    signal_compressed = if signal_expanded > upper_limit
        upper_limit + (math.pow(1 + signal_expanded - upper_limit    , 1 / intensity) - 1)
    else                if signal_expanded < lower_limit
        lower_limit - (math.pow(1 + lower_limit     - signal_expanded, 1 / intensity) - 1)
    else
        signal_expanded


    signal_compressed


limiter(float signal, float lower_limit, float upper_limit, float intensity) =>
    signal_driven = if signal > 1
        math.pow(signal,     upper_limit)
    else if signal < 1
        math.pow(signal, 1 / lower_limit)
    else
        signal

    signal_limited = if signal_driven > upper_limit
        // math.min(signal_driven, upper_limit)
        soft_min(signal_driven, upper_limit, intensity)
    else             if signal_driven < lower_limit
        // math.max(signal_driven, lower_limit)
        soft_max(signal_driven, lower_limit, intensity)
    else
        signal_driven


    signal_limited
//  dependencies........................................................................................................


//  data interval logic.................................................................................................
anchor  = input.string('24h', 'anchor',
 ['1', '5', '24h', 'Session', 'Year', 'Cumulative', 'Moving window', 'Custom session'], group = 'interval')

window  = input        (72         , 'moving window length' , group = 'interval')
session = input.session('0000-2345', 'custom session period', group = 'interval')
hybrid  = input        (false      , 'hybrid window'        , group = 'interval')

isNewPeriod = switch anchor
    '1'       => timeframe.change('1'   )
    '5'       => timeframe.change('5'   )
    '24h'     => timeframe.change('1440')
	'Session' => timeframe.change('D'   )
	'Year'    => timeframe.change('12M' )

if na(close[1])
	isNewPeriod := true

var barsInSession = 0
barsInSession    := isNewPeriod ? 1 : 1 + barsInSession

var barsInSessionCustom = 0
barsInSessionCustom    := na(time('', session)) ? 1 : 1 + barsInSessionCustom

len = if anchor == 'Cumulative'
    bar_index + 1
else  if anchor == 'Moving window'
    window
else  if anchor == 'Custom session'
    barsInSessionCustom
else
    barsInSession + (hybrid ? window : 0)

// len := len > bar_index + 1 ? bar_index + 1 : len
//  data interval logic.................................................................................................


//  main................................................................................................................
step_space = input(1    , 'native tick size multiplier' , group = 'data'      ) * syminfo.mintick  //  space has to be ceiled
round      = input(false, 'round levels to closest tick', group = 'parameters')
online     = input(false, 'recursive version'           , group = 'parameters')


hlc3_ = (round_to_inf(high, step_space) + round_to_inf(low, step_space) + round_to_inf(close, step_space)) / 3
n     =   int(math.pow(len, 0.5))  //  maybe can be improved with some geometric lightweght actual hurst instead of 0.5, but not sure if it's the right thing
src   = entropic_filter(hlc3_, n)  //  this is Not "filtered" src tho, this is our 'new' src, original src is now disregarded like it never been there before

[neg_rr_lag, pos_rr_lag, neg_rr_lead, pos_rr_lead, envelope] = vapm(src, len, online)


// mean_neg_gamma_lead = math.pow(len, -1 / 6 )  //  maybe this worth researching
// mean_neg_gamma_lag  = math.pow(len,  1 / 12)  //  maybe this worth researching
// mean_pos_gamma_lag  = math.pow(len,  1 / 12)  //  maybe this worth researching
// mean_pos_gamma_lead = math.pow(len, -1 / 6 )  //  maybe this worth researching

mean_neg_gamma_lead = 1
mean_neg_gamma_lag  = 1
mean_pos_gamma_lag  = 1
mean_pos_gamma_lead = 1

compressor_upper_neg_gamma_lead = mean_neg_gamma_lead * ((math.log(len + 1) / math.log(2)) / 2)
compressor_upper_neg_gamma_lag  = mean_neg_gamma_lag  * ((math.log(len + 1) / math.log(2)) / 2)
compressor_upper_pos_gamma_lag  = mean_pos_gamma_lag  * ((math.log(len + 1) / math.log(2)) / 2)
compressor_upper_pos_gamma_lead = mean_pos_gamma_lead * ((math.log(len + 1) / math.log(2)) / 2)

compressor_lower_neg_gamma_lead = mean_neg_gamma_lead / 2 
compressor_lower_neg_gamma_lag  = mean_neg_gamma_lag  / 2 
compressor_lower_pos_gamma_lag  = mean_pos_gamma_lag  / 2 
compressor_lower_pos_gamma_lead = mean_pos_gamma_lead / 2 

limiter_upper_neg_gamma_lead = mean_neg_gamma_lead * ((math.log(len + 1) / math.log(2)) / 1)
limiter_upper_neg_gamma_lag  = mean_neg_gamma_lag  * ((math.log(len + 1) / math.log(2)) / 1)
limiter_upper_pos_gamma_lag  = mean_pos_gamma_lag  * ((math.log(len + 1) / math.log(2)) / 1)
limiter_upper_pos_gamma_lead = mean_pos_gamma_lead * ((math.log(len + 1) / math.log(2)) / 1)

limiter_lower_neg_gamma_lead = mean_neg_gamma_lead / 1 
limiter_lower_neg_gamma_lag  = mean_neg_gamma_lag  / 1 
limiter_lower_pos_gamma_lag  = mean_pos_gamma_lag  / 1 
limiter_lower_pos_gamma_lead = mean_pos_gamma_lead / 1 


intensity = math.sqrt(len + 1)

neg_gamma_lead = compressor(neg_rr_lead, compressor_lower_neg_gamma_lead, compressor_upper_neg_gamma_lead, intensity)
neg_gamma_lag  = compressor(neg_rr_lag , compressor_lower_neg_gamma_lag , compressor_upper_neg_gamma_lag , intensity)
pos_gamma_lag  = compressor(pos_rr_lag , compressor_lower_pos_gamma_lag , compressor_upper_pos_gamma_lag , intensity)
pos_gamma_lead = compressor(pos_rr_lead, compressor_lower_pos_gamma_lead, compressor_upper_pos_gamma_lead, intensity)

neg_gamma_lead := limiter(neg_gamma_lead, limiter_lower_neg_gamma_lead, limiter_upper_neg_gamma_lead, intensity)
neg_gamma_lag  := limiter(neg_gamma_lag , limiter_lower_neg_gamma_lag , limiter_upper_neg_gamma_lag , intensity)
pos_gamma_lag  := limiter(pos_gamma_lag , limiter_lower_pos_gamma_lag , limiter_upper_pos_gamma_lag , intensity)
pos_gamma_lead := limiter(pos_gamma_lead, limiter_lower_pos_gamma_lead, limiter_upper_pos_gamma_lead, intensity)


neg_state_lead = online ? universal_adaptive_tracking_online(src, len, neg_gamma_lead) : universal_adaptive_tracking(src, len, neg_gamma_lead)
neg_state_lag  = online ? universal_adaptive_tracking_online(src, len, neg_gamma_lag ) : universal_adaptive_tracking(src, len, neg_gamma_lag )
pos_state_lag  = online ? universal_adaptive_tracking_online(src, len, pos_gamma_lag ) : universal_adaptive_tracking(src, len, pos_gamma_lag )
pos_state_lead = online ? universal_adaptive_tracking_online(src, len, pos_gamma_lead) : universal_adaptive_tracking(src, len, pos_gamma_lead)


neg_state = (neg_state_lag + neg_state_lead) / 2
pos_state = (pos_state_lag + pos_state_lead) / 2

if round
    neg_state := round(neg_state, step_space)
    pos_state := round(pos_state, step_space)
//  main................................................................................................................


//  visuals.............................................................................................................
viz_off = input(0, 'plotting offset', group = 'style')


plot(src, 'src', color.white, 1, plot.style_cross, join = true, force_overlay = true)

plot(envelope.lower, 'lower env', color.purple, display = display.none, force_overlay = true)
plot(envelope.upper, 'upper env', color.purple, display = display.none, force_overlay = true)

plot(neg_state , 'neg state' , color.red , 2, plot.style_line, offset = viz_off, force_overlay = true)
plot(pos_state , 'pos state' , color.blue, 2, plot.style_line, offset = viz_off, force_overlay = true)

plot(src - neg_state, 'price - neg_state', color.red )
plot(src - pos_state, 'price - pos_state', color.blue)


// plot(neg_gamma_lead, 'neg_gamma_lead', color.red   , 1, plot.style_line)
// plot(neg_gamma_lag , 'neg_gamma_lag ', color.maroon, 1, plot.style_line)
// plot(pos_gamma_lag , 'pos_gamma_lag ', color.navy  , 1, plot.style_line)
// plot(pos_gamma_lead, 'pos_gamma_lead', color.blue  , 1, plot.style_line)

// plot(ta.percentile_nearest_rank(neg_gamma_lead, 4994, 50), 'med neg_gamma_lead', color.red   )
// plot(ta.percentile_nearest_rank(neg_gamma_lag , 4994, 50), 'med neg_gamma_lag ', color.maroon)
// plot(ta.percentile_nearest_rank(pos_gamma_lag , 4994, 50), 'med pos_gamma_lag ', color.navy  )
// plot(ta.percentile_nearest_rank(pos_gamma_lead, 4994, 50), 'med pos_gamma_lead', color.blue  )

// plot(ta.stdev(neg_gamma_lead, 4994), 'stdev neg_gamma_lead', color.red   , linestyle = plot.linestyle_dotted)
// plot(ta.stdev(neg_gamma_lag , 4994), 'stdev neg_gamma_lag ', color.maroon, linestyle = plot.linestyle_dotted)
// plot(ta.stdev(pos_gamma_lag , 4994), 'stdev pos_gamma_lag ', color.navy  , linestyle = plot.linestyle_dotted)
// plot(ta.stdev(pos_gamma_lead, 4994), 'stdev pos_gamma_lead', color.blue  , linestyle = plot.linestyle_dotted)

// plot(ta.sma(neg_gamma_lead, 4994), 'avg neg_gamma_lead', color.red   )
// plot(ta.sma(neg_gamma_lag , 4994), 'avg neg_gamma_lag ', color.maroon)
// plot(ta.sma(pos_gamma_lag , 4994), 'avg pos_gamma_lag ', color.navy  )
// plot(ta.sma(pos_gamma_lead, 4994), 'avg pos_gamma_lead', color.blue  )

// plot(compressor_upper_neg_gamma_lead, 'neg_rr_lead comp', color.red   , linestyle = plot.linestyle_dashed)
// plot(compressor_upper_neg_gamma_lag , 'neg_rr_lag  comp', color.maroon, linestyle = plot.linestyle_dashed)
// plot(compressor_upper_pos_gamma_lag , 'pos_rr_lag  comp', color.navy  , linestyle = plot.linestyle_dashed)
// plot(compressor_upper_pos_gamma_lead, 'pos_rr_lead comp', color.blue  , linestyle = plot.linestyle_dashed)

// plot(limiter_upper_neg_gamma_lead, 'neg_rr_lead lim', color.red   )
// plot(limiter_upper_neg_gamma_lag , 'neg_rr_lag  lim', color.maroon)
// plot(limiter_upper_pos_gamma_lag , 'pos_rr_lag  lim', color.navy  )
// plot(limiter_upper_pos_gamma_lead, 'pos_rr_lead lim', color.blue  )

// plot(neg_state_lead, 'neg_state_lead')
// plot(neg_state_lag , 'neg_state_lag ')
// plot(pos_state_lag , 'pos_state_lag ')
// plot(pos_state_lead, 'pos_state_lead')

hline(  0)
// hline(0.5)
// hline(  1)
// hline(1.5)
// hline(  2)


// plot(ta.cum(math.abs(neg_state - pos_state)), 'er', display = display.status_line)
//  visuals.............................................................................................................


//  ∞
